# hash-identificacao: 10f31d02f7632a527ced87a8a16a60109e7a7f6e9d2bb530dc8fff7f2f538918

# Configurações padrão disponíveis: https://docs.spring.io/spring-boot/appendix/application-properties/index.html

spring.application.name=dados-pessoais

# --- Servidor Web ---
# server.port=8080
# server.servlet.context-path=/  # Opcional: definir um contexto base para a API

# --- Jackson (serialização JSON formatada) ---
spring.jackson.serialization.INDENT_OUTPUT=true

# Formata o JSON das respostas com indenta��o
spring.jackson.serialization.INDENT_OUTPUT=true
